#!/usr/bin/env python3
"""
MR. CHAMELEON — script sync.

SCRIPT.md is the single hand-edited source. This recomputes everything derived from it:

  * every block's film-time in/out, from the block durations in running order
  * every VO line's absolute film timecode, from its +Ns offset inside its block
  * the "все реплики подряд" table at the bottom of SCRIPT.md
  * NARRATION.md, regenerated from scratch
  * the total runtime, everywhere it is printed

It also runs two guards:

  * no VO line text may appear anywhere in SHOTLIST_PROMPTS.md — narration must never
    reach a prompt
  * every VO offset must fall inside its own block

Run:  python3 sync_script.py
"""

import re
import sys
from pathlib import Path

HERE = Path(__file__).parent
SCRIPT = HERE / "SCRIPT.md"
NARRATION = HERE / "NARRATION.md"
SHOTLIST = HERE / "SHOTLIST_PROMPTS.md"

BLOCK_RE = re.compile(
    r"^## (?P<id>\S+) · (?P<name>.+?) — (?P<len>[\d.]+) сек · \*\*\d+:\d\d → \d+:\d\d\*\*$"
)
VO_RE = re.compile(
    r"^> \*\*(?P<tag>VO-\d+)\*\* · \+(?P<off>[\d.]+)s · `[^`]*` · (?P<text>.*)$"
)
AUTOGEN_MARK = "<!-- AUTOGENERATED BELOW — не править руками, перезапишется -->"


def tc(seconds):
    seconds = int(round(seconds))
    return f"{seconds // 60}:{seconds % 60:02d}"


def plain(text):
    """Strip markdown emphasis so the line can be compared against the shotlist."""
    return re.sub(r"[*`]", "", text).strip()


def main():
    lines = SCRIPT.read_text(encoding="utf-8").split("\n")

    # ---- pass 1: walk the file, accumulate time, rewrite derived numbers -------
    clock = 0.0
    blocks = []          # (id, name, length, start)
    cues = []            # (tag, block_id, block_name, abs_seconds, text)
    current = None
    problems = []
    out = []
    in_fence = False

    for line in lines:
        if line.strip() == AUTOGEN_MARK:
            out.append(line)
            break

        # fenced code is documentation (the format examples) — never parsed as content
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
            out.append(line)
            continue
        if in_fence:
            out.append(line)
            continue

        bm = BLOCK_RE.match(line)
        if bm:
            length = float(bm.group("len"))
            start = clock
            current = (bm.group("id"), bm.group("name"), length, start)
            blocks.append(current)
            clock += length
            length_txt = bm.group("len")
            line = (
                f"## {bm.group('id')} · {bm.group('name')} — {length_txt} сек · "
                f"**{tc(start)} → {tc(clock)}**"
            )
            out.append(line)
            continue

        vm = VO_RE.match(line)
        if vm:
            if current is None:
                problems.append(f"{vm.group('tag')} стоит до первого блока")
                out.append(line)
                continue
            off = float(vm.group("off"))
            bid, bname, blen, bstart = current
            if off > blen:
                problems.append(
                    f"{vm.group('tag')}: +{off}s выходит за блок {bid} ({blen:g} сек)"
                )
            abs_s = bstart + off
            cues.append((vm.group("tag"), bid, bname, abs_s, vm.group("text")))
            off_txt = vm.group("off")
            line = (
                f"> **{vm.group('tag')}** · +{off_txt}s · `{tc(abs_s)}` · {vm.group('text')}"
            )
        out.append(line)

    total = clock

    # ---- pass 2: rebuild the autogenerated tail of SCRIPT.md ------------------
    tail = ["", "Для записи озвучки. Считается автоматически — правь реплики выше по тексту.", ""]
    tail.append("| # | Таймкод | Блок | Реплика |")
    tail.append("|---|---|---|---|")
    for tag, bid, bname, abs_s, text in cues:
        tail.append(f"| {tag} | {tc(abs_s)} | {bid} · {bname} | {plain(text)} |")
    tail += ["", f"**Всего:** {len(cues)} реплик · хронометраж фильма **{tc(total)}** ({int(total)} сек)", ""]

    out.append("")
    out += tail
    SCRIPT.write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")

    # ---- pass 3: regenerate NARRATION.md -------------------------------------
    n = [
        "# MR. CHAMELEON — NARRATION",
        "",
        "> **СГЕНЕРИРОВАНО ИЗ `SCRIPT.md`. НЕ ПРАВИТЬ.**",
        "> Любая правка здесь пропадёт при следующем пересчёте. Реплики живут в `SCRIPT.md`,",
        "> каждая на своём месте в кадре.",
        "",
        "**Записывается отдельно живым голосом. Никогда не генерируется и никогда не попадает в промпт.**",
        "В каждом промпте стоит `No narration`.",
        "",
        f"**Реплик:** {len(cues)} · **Первая:** {tc(cues[0][3])} · **Последняя:** {tc(cues[-1][3])} · "
        f"**Хронометраж:** {tc(total)}",
        "",
        "| # | Таймкод | Над чем идёт | Реплика |",
        "|---|---|---|---|",
    ]
    for tag, bid, bname, abs_s, text in cues:
        n.append(f"| {tag} | {tc(abs_s)} | {bid} · {bname} | {plain(text)} |")
    n += [
        "",
        "## Голос",
        "",
        "Ровный, неспешный, тихий. Никакой игры. Он показывает знакомому свою квартиру. Ужас в том, что он",
        "говорит это всерьёз.",
        "",
        "**Единственная реплика с изломом — последняя.** «But I am still good old me» — закрыто и уверенно,",
        "поверх крика. Пауза настоящая, около секунды. «Or am I?» — тише, не громче, вниз, почти себе под нос.",
        "",
        "## Пост",
        "",
        "Нарратор сухой и близкий, сидит поверх сгенерированной атмосферы. Музыки нет нигде.",
        "Крик в генерации 11 — сгенерированный, настоящий, из самого кадра; он выходит вперёд на склейке в чёрное.",
        "",
    ]
    NARRATION.write_text("\n".join(n), encoding="utf-8")

    # ---- guards ---------------------------------------------------------------
    leaks = []
    if SHOTLIST.exists():
        # only what is inside ``` fences matters — that is the text pasted into Seedance.
        # prose around the prompts may discuss the narration freely.
        raw = SHOTLIST.read_text(encoding="utf-8").split("\n")
        fenced, on = [], False
        for ln in raw:
            if ln.lstrip().startswith("```"):
                on = not on
                continue
            if on:
                fenced.append(ln)
        shot = "\n".join(fenced)
        for tag, _bid, _bname, _abs_s, text in cues:
            needle = plain(text).strip('"').split('"')[0].strip()
            if len(needle) > 12 and needle in shot:
                leaks.append(f"{tag}: «{needle[:40]}…» найдено в SHOTLIST_PROMPTS.md")

    print(f"Блоков: {len(blocks)}  ·  реплик: {len(cues)}  ·  хронометраж: {tc(total)} ({int(total)} сек)")
    for tag, bid, _bn, abs_s, _t in cues:
        print(f"  {tag}  {tc(abs_s)}  ({bid})")

    if problems:
        print("\nПРОБЛЕМЫ:")
        for p in problems:
            print("  ! " + p)
    if leaks:
        print("\nНАРРАТОР ПРОТЁК В ПРОМПТЫ:")
        for l in leaks:
            print("  ! " + l)
    if problems or leaks:
        sys.exit(1)
    print("\nОК. NARRATION.md перезаписан.")


if __name__ == "__main__":
    main()
